require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/seeds.rb
    - vendor/**/*
    - spec/features/**/*

Layout/LineLength:
  Max: 120
  Exclude:
    - lib/udatapp/api_current_container.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - Gemfile

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 50
  Exclude:
    - db/seeds.rb

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Exclude:
    - db/seeds.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - db/seeds.rb

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - config/environments/**/*
    - config/routes.rb
    - db/**/*
    - spec/**/*

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

RSpec/ScatteredSetup:
  Exclude:
    - spec/requests/**/*_spec.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10
  Exclude:
    - spec/api/**/*

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - spec/api/**/*

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - and

RSpec/NestedGroups:
  Max: 6

RSpec/MessageSpies:
  Enabled: false
